import { nanoid } from "nanoid";

export const flyersItems = [
  {
    id: nanoid(),
    heading: "Show",
    color: "#1aae7a",
  },
  {
    id: nanoid(),
    heading: "And",
    color: "#f6aa9f",
  },
  {
    id: nanoid(),
    heading: "Tell",
    color: "#006dff",
  },
];

export const eventsItemsDetails = [
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "30.09.23",
    locality: "Theatre Severn",
    city: "Shrewbury",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$10",
  },
  {
    id: nanoid(),
    group: "Austentatious",
    gamesName: "An Improvised Jane Austen Novel",
    date: "02.10.23",
    locality: "Arts Theatre West End",
    city: "London",
    photoNormal: "../src/assets/austentatious.png",
    photoSmall: "../src/assets/austentatious-small.jpeg",
    photoBig: "../src/assets/austentatious-big.jpg",
    price: "$12",
  },
  {
    id: nanoid(),
    group: "Peckham Playground",
    gamesName: "with Nish Kumar",
    date: "05.10.23",
    locality: "Copeland Park, Peckham",
    city: "Oxford",
    photoNormal: "../src/assets/phil-wang.png",
    photoSmall: "../src/assets/phil-wang-small.png",
    photoBig: "../src/assets/phil-wang-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Peckham Playground",
    gamesName: "Comedy of Black Origin",
    date: "06.10.23",
    locality: "Copeland Park, Peckham",
    city: "London",
    photoNormal: "../src/assets/blackwood.png",
    photoSmall: "../src/assets/blackwood-small.png",
    photoBig: "../src/assets/blackwood-big.png",
    price: "$10",
  },
  {
    id: nanoid(),
    group: "Peckham Playground",
    gamesName: "with Stewart Lee",
    date: "07.10.23",
    locality: "Copeland Park, Peckham",
    city: "London",
    photoNormal: "../src/assets/stewart-lee.png",
    photoSmall: "../src/assets/stewart-lee-small.png",
    photoBig: "../src/assets/stewart-lee-big.png",
    price: "$14",
  },
  {
    id: nanoid(),
    group: "Peckham Playground",
    gamesName: "with Ed Gamble",
    date: "07.10.23",
    locality: "Copeland Park, Peckham",
    city: "London",
    photoNormal: "../src/assets/gamble.png",
    photoSmall: "../src/assets/gamble-small.png",
    photoBig: "../src/assets/gamble-big.png",
    price: "$20",
  },
  {
    id: nanoid(),
    group: "Peckham Playground",
    gamesName: "Say Your Mind Podcast Live",
    date: "07.10.23",
    locality: "Copeland Park, Peckham",
    city: "London",
    photoNormal: "../src/assets/kelechi.png",
    photoSmall: "../src/assets/kelechi-small.png",
    photoBig: "../src/assets/kelechi-big.png",
    price: "$23",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "07.10.23",
    locality: "The Fire Station",
    city: "Sunderland",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$10",
  },
  {
    id: nanoid(),
    group: "Peckham Playground",
    gamesName: "with Fern Brady",
    date: "08.10.23",
    locality: "Copeland Park, Peckham",
    city: "London",
    photoNormal: "../src/assets/fern-brady.png",
    photoSmall: "../src/assets/fern-brady-small.png",
    photoBig: "../src/assets/fern-brady-big.png",
    price: "$19",
  },
  {
    id: nanoid(),
    group: "Peckham Playground",
    gamesName: "with Phil Wang",
    date: "08.10.23",
    locality: "Copeland Park, Peckham",
    city: "London",
    photoNormal: "../src/assets/phil-wang.png",
    photoSmall: "../src/assets/phil-wang-small.png",
    photoBig: "../src/assets/phil-wang-big.png",
    price: "$11",
  },
  {
    id: nanoid(),
    group: "No Direction Home",
    gamesName: "with Catherine Bohart",
    date: "09.10.23",
    locality: "Soho Theatre",
    city: "Oxford",
    photoNormal: "../src/assets/catherine.png",
    photoSmall: "../src/assets/catherine-small.png",
    photoBig: "../src/assets/micheal-akadiri-big.jpg",
    price: "$10",
  },
  {
    id: nanoid(),
    group: "Austentatious",
    gamesName: "An Improvised Jane Austen Novel",
    date: "09.10.23",
    locality: "Arts Theatre West End",
    city: "London",
    photoNormal: "../src/assets/austentatious.png",
    photoSmall: "../src/assets/austentatious-small.jpeg",
    photoBig: "../src/assets/austentatious-big.jpg",
    price: "$27",
  },
  {
    id: nanoid(),
    group: "Tim Key",
    gamesName: "Mulberry",
    date: "11.10.23",
    locality: "SoHo Playhouse",
    city: "New York (NYC)",
    photoNormal: "../src/assets/tim-key.jpeg",
    photoSmall: "../src/assets/tim-key-small.jpeg",
    photoBig: "../src/assets/tim-key-big.jpg",
    price: "$24",
  },
  {
    id: nanoid(),
    group: "Tim Key",
    gamesName: "Mulberry",
    date: "12.10.23",
    locality: "SoHo Playhouse",
    city: "New York (NYC)",
    photoNormal: "../src/assets/tim-key.jpeg",
    photoSmall: "../src/assets/tim-key-small.jpeg",
    photoBig: "../src/assets/tim-key-big.jpg",
    price: "$20",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "12.10.23",
    locality: "The Old Rep Theatre",
    city: "Birmingham",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$10",
  },
  {
    id: nanoid(),
    group: "Tim Key",
    gamesName: "Mulberry",
    date: "11.10.23",
    locality: "SoHo Playhouse",
    city: "New York (NYC)",
    photoNormal: "../src/assets/tim-key.jpeg",
    photoSmall: "../src/assets/tim-key-small.jpeg",
    photoBig: "../src/assets/tim-key-big.jpg",
    price: "$14",
  },
  {
    id: nanoid(),
    group: "Tim Key",
    gamesName: "Mulberry",
    date: "13.10.23",
    locality: "SoHo Playhouse",
    city: "New York (NYC)",
    photoNormal: "../src/assets/tim-key.jpeg",
    photoSmall: "../src/assets/tim-key-small.jpeg",
    photoBig: "../src/assets/tim-key-big.jpg",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Tim Key",
    gamesName: "Mulberry",
    date: "14.10.23",
    locality: "SoHo Playhouse",
    city: "New York (NYC)",
    photoNormal: "../src/assets/tim-key.jpeg",
    photoSmall: "../src/assets/tim-key-small.jpeg",
    photoBig: "../src/assets/tim-key-big.jpg",
    price: "$11",
  },
  {
    id: nanoid(),
    group: "Bush Hall Present",
    gamesName: "with Kerry Godliman",
    date: "20.10.23",
    locality: "Bush Hall",
    city: "Oxford",
    photoNormal: "../src/assets/kerry-godliman.png",
    photoSmall: "../src/assets/kerry-godliman-small.png",
    photoBig: "../src/assets/kerry-godliman-big.png",
    price: "$16",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "21.10.23",
    locality: "Arts Centre",
    city: "Swindon",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$19",
  },
  {
    id: nanoid(),
    group: "Rachel Parris",
    gamesName: "Fool's Gold",
    date: "23.10.23",
    locality: "The Old Rep Theatre",
    city: "Birmingham",
    photoNormal: "../src/assets/rachel-parris.png",
    photoSmall: "../src/assets/rachel-parris-small.png",
    photoBig: "../src/assets/rachel-parris-big.png",
    price: "$21",
  },
  {
    id: nanoid(),
    group: "Rachel Parris",
    gamesName: "Fool's Gold",
    date: "23.10.23",
    locality: "The Old Rep Theatre",
    city: "Birmingham",
    photoNormal: "../src/assets/rachel-parris.png",
    photoSmall: "../src/assets/rachel-parris-small.png",
    photoBig: "../src/assets/rachel-parris-big.png",
    price: "$23",
  },
  {
    id: nanoid(),
    group: "Austentatious",
    gamesName: "An Improvised Jane Austen Novel",
    date: "25.10.23",
    locality: "Arts Theatre West End",
    city: "London",
    photoNormal: "../src/assets/austentatious.png",
    photoSmall: "../src/assets/austentatious-small.jpeg",
    photoBig: "../src/assets/austentatious-big.jpg",
    price: "$30",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "25.10.23",
    locality: "Guildhall",
    city: "Gloucester",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$10",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "26.10.23",
    locality: "Huntingdon Hall",
    city: "Worcester",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "27.10.23",
    locality: "Corn Exchange",
    city: "Newbury",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$19",
  },
  {
    id: nanoid(),
    group: "Austentatious",
    gamesName: "An Improvised Jane Austen Novel",
    date: "30.10.23",
    locality: "Arts Theatre West End",
    city: "London",
    photoNormal: "../src/assets/austentatious.png",
    photoSmall: "../src/assets/austentatious-small.jpeg",
    photoBig: "../src/assets/austentatious-big.jpg",
    price: "$14",
  },
  {
    id: nanoid(),
    group: "Ramy Youssef",
    gamesName: "More Feelings",
    date: "03.11.23",
    locality: "Hackney Empire",
    city: "London",
    photoNormal: "../src/assets/ramy-youssef.png",
    photoSmall: "../src/assets/ramy-youssef-small.png",
    photoBig: "../src/assets/ramy-youssef-big.png",
    price: "$12",
  },
  {
    id: nanoid(),
    group: "Ramy Youssef",
    gamesName: "More Feelings",
    date: "03.11.23",
    locality: "Hackney Empire",
    city: "London",
    photoNormal: "../src/assets/ramy-youssef.png",
    photoSmall: "../src/assets/ramy-youssef-small.png",
    photoBig: "../src/assets/ramy-youssef-big.png",
    price: "$11",
  },
  {
    id: nanoid(),
    group: "Ramy Youssef",
    gamesName: "More Feelings",
    date: "03.11.23",
    locality: "Hackney Empire",
    city: "London",
    photoNormal: "../src/assets/ramy-youssef.png",
    photoSmall: "../src/assets/ramy-youssef-small.png",
    photoBig: "../src/assets/ramy-youssef-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Ramy Youssef",
    gamesName: "More Feelings",
    date: "03.11.23",
    locality: "Hackney Empire",
    city: "London",
    photoNormal: "../src/assets/ramy-youssef.png",
    photoSmall: "../src/assets/ramy-youssef-small.png",
    photoBig: "../src/assets/ramy-youssef-big.png",
    price: "$30",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "04.11.23",
    locality: "The Lights",
    city: "Andover",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$23",
  },
  {
    id: nanoid(),
    group: "Austentatious",
    gamesName: "An Improvised Jane Austen Novel",
    date: "06.11.23",
    locality: "Arts Theatre West End",
    city: "London",
    photoNormal: "../src/assets/austentatious.png",
    photoSmall: "../src/assets/austentatious-small.jpeg",
    photoBig: "../src/assets/austentatious-big.jpg",
    price: "$28",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "09.11.23",
    locality: "The Dukes",
    city: "Lancaster",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$21",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "10.11.23",
    locality: "New Century Hall",
    city: "Manchester",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$20",
  },
  {
    id: nanoid(),
    group: "No Direction Home",
    gamesName: "with Micheal Akadiri",
    date: "13.11.23",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/michael-akadiri.png",
    photoSmall: "../src/assets/micheal-akadiri-small.png",
    photoBig: "../src/assets/micheal-akadiri-big.jpg",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Austentatious",
    gamesName: "An Improvised Jane Austen Novel",
    date: "13.11.23",
    locality: "Arts Theatre West End",
    city: "Manchester",
    photoNormal: "../src/assets/austentatious.png",
    photoSmall: "../src/assets/austentatious-small.jpeg",
    photoBig: "../src/assets/austentatious-big.jpg",
    price: "$11",
  },
  {
    id: nanoid(),
    group: "Leila Navabi",
    gamesName: "Composition",
    date: "14.11.23",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/leila-navabi.jpeg",
    photoSmall: "../src/assets/leila-navabi-small.jpeg",
    photoBig: "../src/assets/leila-navabi-big.jpg",
    price: "$16",
  },
  {
    id: nanoid(),
    group: "Leila Navabi",
    gamesName: "Composition",
    date: "15.11.23",
    locality: "Soho Theatre",
    city: "Manchester",
    photoNormal: "../src/assets/leila-navabi.jpeg",
    photoSmall: "../src/assets/leila-navabi-small.jpeg",
    photoBig: "../src/assets/leila-navabi-big.jpg",
    price: "$30",
  },
  {
    id: nanoid(),
    group: "Leila Navabi",
    gamesName: "Composition",
    date: "16.11.23",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/leila-navabi.jpeg",
    photoSmall: "../src/assets/leila-navabi-small.jpeg",
    photoBig: "../src/assets/leila-navabi-big.jpg",
    price: "$28",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "16.11.23",
    locality: "MAST Studio",
    city: "Southampton",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Leila Navabi",
    gamesName: "Composition",
    date: "17.11.23",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/leila-navabi.jpeg",
    photoSmall: "../src/assets/leila-navabi-small.jpeg",
    photoBig: "../src/assets/leila-navabi-big.jpg",
    price: "$13",
  },
  {
    id: nanoid(),
    group: "Leila Navabi",
    gamesName: "Composition",
    date: "18.11.23",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/leila-navabi.jpeg",
    photoSmall: "../src/assets/leila-navabi-small.jpeg",
    photoBig: "../src/assets/leila-navabi-big.jpg",
    price: "$14",
  },
  {
    id: nanoid(),
    group: "Austentatious",
    gamesName: "An Improvised Jane Austen Novel",
    date: "20.11.23",
    locality: "Arts Theatre West End",
    city: "London",
    photoNormal: "../src/assets/austentatious.png",
    photoSmall: "../src/assets/austentatious-small.jpeg",
    photoBig: "../src/assets/austentatious-big.jpg",
    price: "$18",
  },
  {
    id: nanoid(),
    group: "Bush Hall Presents",
    gamesName: "with Sindhu Vee",
    date: "24.11.23",
    locality: "Bush Hall",
    city: "Manchester",
    photoNormal: "../src/assets/sindhu-vee.png",
    photoSmall: "../src/assets/sindhu-vee-small.png",
    photoBig: "../src/assets/sindhu-vee-big.jpg",
    price: "$28",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "25.11.23",
    locality: "Royal & Derngate",
    city: "Northampton",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Austentatious",
    gamesName: "An Improvised Jane Austen Novel",
    date: "27.11.23",
    locality: "Arts Theatre West End",
    city: "London",
    photoNormal: "../src/assets/austentatious.png",
    photoSmall: "../src/assets/austentatious-small.jpeg",
    photoBig: "../src/assets/austentatious-big.jpg",
    price: "$10",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "29.11.23",
    locality: "Liberty Hall",
    city: "Dublin",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$11",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "30.11.23",
    locality: "Limelight",
    city: "Belfast",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$13",
  },
  {
    id: nanoid(),
    group: "Rhys James",
    gamesName: "Split Milk",
    date: "03.12.23",
    locality: "Corn Exchange",
    city: "Brighton",
    photoNormal: "../src/assets/rhys.png",
    photoSmall: "../src/assets/rhys-small.jpeg",
    photoBig: "../src/assets/rhys-big.jpg",
    price: "$24",
  },
  {
    id: nanoid(),
    group: "Austentatious",
    gamesName: "An Improvised Jane Austen Novel",
    date: "04.12.23",
    locality: "Arts Theatre West End",
    city: "London",
    photoNormal: "../src/assets/austentatious.png",
    photoSmall: "../src/assets/austentatious-small.jpeg",
    photoBig: "../src/assets/austentatious-big.jpg",
    price: "$30",
  },
  {
    id: nanoid(),
    group: "Janie Harouni",
    gamesName: "Man'oushe",
    date: "05.12.23",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/janie.jpeg",
    photoSmall: "../src/assets/janie-small.png",
    photoBig: "../src/assets/janie-big.png",
    price: "$24",
  },
  {
    id: nanoid(),
    group: "Janie Harouni",
    gamesName: "Man'oushe",
    date: "06.12.23",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/janie.jpeg",
    photoSmall: "../src/assets/janie-small.png",
    photoBig: "../src/assets/janie-big.png",
    price: "$25",
  },
  {
    id: nanoid(),
    group: "Janie Harouni",
    gamesName: "Man'oushe",
    date: "07.12.23",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/janie.jpeg",
    photoSmall: "../src/assets/janie-small.png",
    photoBig: "../src/assets/janie-big.png",
    price: "$15",
  },
  {
    id: nanoid(),
    group: "Janie Harouni",
    gamesName: "Man'oushe",
    date: "08.12.23",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/janie.jpeg",
    photoSmall: "../src/assets/janie-small.png",
    photoBig: "../src/assets/janie-big.png",
    price: "$28",
  },
  {
    id: nanoid(),
    group: "Janie Harouni",
    gamesName: "Man'oushe",
    date: "08.12.23",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/janie.jpeg",
    photoSmall: "../src/assets/janie-small.png",
    photoBig: "../src/assets/janie-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Janie Harouni",
    gamesName: "Man'oushe",
    date: "09.12.23",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/janie.jpeg",
    photoSmall: "../src/assets/janie-small.png",
    photoBig: "../src/assets/janie-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "No Direction Home",
    gamesName: "with Catherine Bohart",
    date: "11.12.23",
    locality: "Soho Theatre",
    city: "Oxford",
    photoNormal: "../src/assets/catherine.png",
    photoSmall: "../src/assets/catherine-small.png",
    photoBig: "../src/assets/micheal-akadiri-big.jpg",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Austentatious",
    gamesName: "An Improvised Jane Austen Novel",
    date: "11.12.23",
    locality: "Arts Theatre West End",
    city: "London",
    photoNormal: "../src/assets/austentatious.png",
    photoSmall: "../src/assets/austentatious-small.jpeg",
    photoBig: "../src/assets/austentatious-big.jpg",
    price: "$26",
  },
  {
    id: nanoid(),
    group: "Austentatious",
    gamesName: "An Improvised Jane Austen Novel",
    date: "18.12.23",
    locality: "Arts Theatre West End",
    city: "London",
    photoNormal: "../src/assets/austentatious.png",
    photoSmall: "../src/assets/austentatious-small.jpeg",
    photoBig: "../src/assets/austentatious-big.jpg",
    price: "$24",
  },
  {
    id: nanoid(),
    group: "Dan Tiernan",
    gamesName: "Going Under",
    date: "10.01.24",
    locality: "Soho Theatre",
    city: "Oxford",
    photoNormal: "../src/assets/dan-tiernan.png",
    photoSmall: "../src/assets/dan-tiernan-small.png",
    photoBig: "../src/assets/dan-tiernan-big.png",
    price: "$30",
  },
  {
    id: nanoid(),
    group: "Dan Tiernan",
    gamesName: "Going Under",
    date: "11.01.24",
    locality: "Soho Theatre",
    city: "Oxford",
    photoNormal: "../src/assets/dan-tiernan.png",
    photoSmall: "../src/assets/dan-tiernan-small.png",
    photoBig: "../src/assets/dan-tiernan-big.png",
    price: "$13",
  },
  {
    id: nanoid(),
    group: "Dan Tiernan",
    gamesName: "Going Under",
    date: "12.01.24",
    locality: "Soho Theatre",
    city: "London",
    photoNormal: "../src/assets/dan-tiernan.png",
    photoSmall: "../src/assets/dan-tiernan-small.png",
    photoBig: "../src/assets/dan-tiernan-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Dan Tiernan",
    gamesName: "Going Under",
    date: "13.01.24",
    locality: "Soho Theatre",
    city: "Oxford",
    photoNormal: "../src/assets/dan-tiernan.png",
    photoSmall: "../src/assets/dan-tiernan-small.png",
    photoBig: "../src/assets/dan-tiernan-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "09.02.24",
    locality: "Y Theatre",
    city: "Leicester",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$10",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "16.02.24",
    locality: "Keay Theatre",
    city: "Plymouth",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "18.02.24",
    locality: "Quad Theatre",
    city: "Plymouth",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "22.02.24",
    locality: "Arts Centre",
    city: "Swindon",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "23.02.24",
    locality: "Leicester Square Theatre",
    city: "London",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "01.03.24",
    locality: "Guildhall",
    city: "Gloucester",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "02.03.24",
    locality: "1532",
    city: "Bristol",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "03.03.24",
    locality: "Wedgewood Rooms",
    city: "Portsmouth",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "08.03.24",
    locality: "The Lowry",
    city: "Salford",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "09.03.24",
    locality: "How water Comedy Club",
    city: "Liverpool",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "14.03.24",
    locality: "Glee",
    city: "Oxford",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "15.03.24",
    locality: "City Varieties",
    city: "Leeds",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "17.04.24",
    locality: "Theatre Royal",
    city: "Winchester",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "18.04.24",
    locality: "The Forge",
    city: "Brighton",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "21.04.24",
    locality: "Glee",
    city: "Birmingham",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "23.04.24",
    locality: "Limelight",
    city: "Belfast",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "24.04.24",
    locality: "Coughlan's",
    city: "Cork",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "25.04.24",
    locality: "Whelan's",
    city: "Dublin",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "30.04.24",
    locality: "The Stand",
    city: "Newcastle",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "01.05.24",
    locality: "The Stand",
    city: "Edinburgh",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "02.05.24",
    locality: "The Stand",
    city: "Glasgow",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "09.05.24",
    locality: "Arts Centre",
    city: "Stockton",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "18.05.24",
    locality: "Junction",
    city: "Cambridge",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "22.05.24",
    locality: "Leadmill",
    city: "Sheffield",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "30.05.24",
    locality: "Little Theatre",
    city: "Chorley",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "01.06.24",
    locality: "Theatre Severn",
    city: "Shrewbury",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "05.06.24",
    locality: "Glee",
    city: "Cardiff",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "06.06.24",
    locality: "Phoenix",
    city: "Exeter",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "07.06.24",
    locality: "Playhouse",
    city: "Norwich",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
  {
    id: nanoid(),
    group: "Fin Taylor",
    gamesName: "Ask Your Mother",
    date: "13.06.24",
    locality: "Arts Centre",
    city: "Colchester",
    photoNormal: "../src/assets/new-fin-taylor.png",
    photoSmall: "../src/assets/new-fin-taylor-small.png",
    photoBig: "../src/assets/new-fin-taylor-big.png",
    price: "$17",
  },
];

export const navLinks = [
  {
    id: nanoid(),
    name: "What's On",
    link: "events",
  },
  {
    id: nanoid(),
    name: "About",
    link: "about",
  },
  {
    id: nanoid(),
    name: "Jobs",
    link: "about/jobs",
  },
  {
    id: nanoid(),
    name: "Archive",
    link: "about/archive",
  },
];

export const eventCities = [
  {
    id: nanoid(),
    city: "Andover",
    link: "andover",
  },
  {
    id: nanoid(),
    city: "Bernard Castle",
    link: "bernard-castle",
  },
  {
    id: nanoid(),
    city: "Belfast",
    link: "belfast",
  },
  {
    id: nanoid(),
    city: "Birmingham",
    link: "birmingham",
  },
  {
    id: nanoid(),
    city: "Brighton",
    link: "brighton",
  },
  {
    id: nanoid(),
    city: "Bristol",
    link: "bristol",
  },
  {
    id: nanoid(),
    city: "Cambrdige",
    link: "cambridge",
  },
  {
    id: nanoid(),
    city: "Cardiff",
    link: "cardiff",
  },
  {
    id: nanoid(),
    city: "Canterbury",
    link: "canterbury",
  },
  {
    id: nanoid(),
    city: "Chelmsford",
    link: "chelmsford",
  },
  {
    id: nanoid(),
    city: "Chorley",
    link: "chorley",
  },
  {
    id: nanoid(),
    city: "Cork",
    link: "cork",
  },
  {
    id: nanoid(),
    city: "Coventry",
    link: "coventry",
  },
  {
    id: nanoid(),
    city: "Dublin",
    link: "dublin",
  },
  {
    id: nanoid(),
    city: "Edinburgh",
    link: "edinburgh",
  },
  {
    id: nanoid(),
    city: "Exeter",
    link: "exeter",
  },
  {
    id: nanoid(),
    city: "Folkestone",
    link: "folkestone",
  },
  {
    id: nanoid(),
    city: "Glasgow",
    link: "glasgow",
  },
  {
    id: nanoid(),
    city: "Gloucester",
    link: "gloucester",
  },
  {
    id: nanoid(),
    city: "Henly-On-Thames",
    link: "henly-on-thames",
  },
  {
    id: nanoid(),
    city: "Hexham",
    link: "hexham",
  },
  {
    id: nanoid(),
    city: "Horsham",
    link: "horsham",
  },
  {
    id: nanoid(),
    city: "Hull",
    link: "hull",
  },
  {
    id: nanoid(),
    city: "Kendal",
    link: "kendal",
  },
  {
    id: nanoid(),
    city: "Lancaster",
    link: "lancaster",
  },
  {
    id: nanoid(),
    city: "Leeds",
    link: "leeds",
  },
  {
    id: nanoid(),
    city: "Leicester",
    link: "leicester",
  },
  {
    id: nanoid(),
    city: "Lincoln",
    link: "lincoln",
  },
  {
    id: nanoid(),
    city: "Liverpool",
    link: "liverpool",
  },
  {
    id: nanoid(),
    city: "London",
    link: "london",
  },
  {
    id: nanoid(),
    city: "Maidenhead",
    link: "maidenhead",
  },
  {
    id: nanoid(),
    city: "Manchester",
    link: "manchester",
  },
  {
    id: nanoid(),
    city: "Newbury",
    link: "newbury",
  },
  {
    id: nanoid(),
    city: "Newcastle",
    link: "newcastle",
  },
  {
    id: nanoid(),
    city: "Northampton",
    link: "northampton",
  },
  {
    id: nanoid(),
    city: "Northallerton",
    link: "northallerton",
  },
  {
    id: nanoid(),
    city: "Norwich",
    link: "norwich",
  },
  {
    id: nanoid(),
    city: "Nottingham",
    link: "nottingham",
  },
  {
    id: nanoid(),
    city: "Oxford",
    link: "oxford",
  },
  {
    id: nanoid(),
    city: "Plymouth",
    link: "plymouth",
  },
  {
    id: nanoid(),
    city: "Portsmouth",
    link: "portsmouth",
  },
  {
    id: nanoid(),
    city: "Reading",
    link: "reading",
  },
  {
    id: nanoid(),
    city: "Salford",
    link: "salford",
  },
  {
    id: nanoid(),
    city: "Sheffield",
    link: "sheffield",
  },
  {
    id: nanoid(),
    city: "Shrewbury",
    link: "shrewbury",
  },
  {
    id: nanoid(),
    city: "Southampton",
    link: "southampton",
  },
  {
    id: nanoid(),
    city: "St Austell",
    link: "st-austell",
  },
  {
    id: nanoid(),
    city: "Stafford",
    link: "stafford",
  },
  {
    id: nanoid(),
    city: "Stockton",
    link: "stockton",
  },
  {
    id: nanoid(),
    city: "Sunderland",
    link: "sunderland",
  },
  {
    id: nanoid(),
    city: "Southport",
    link: "southport",
  },
  {
    id: nanoid(),
    city: "Swindon",
    link: "swindon",
  },
  {
    id: nanoid(),
    city: "Tunbridge Wells",
    link: "tunbridge-wells",
  },
  {
    id: nanoid(),
    city: "Wells",
    link: "wells",
  },
  {
    id: nanoid(),
    city: "Winchester",
    link: "winchester",
  },
  {
    id: nanoid(),
    city: "Worcester",
    link: "worcester",
  },
  {
    id: nanoid(),
    city: "New York (NYC)",
    link: "new-york",
  },
];

export const footerItems = [
  {
    id: nanoid(),
    headingAdress: "UK",
    company: "Show And Tell Productions Ltd",
    region: "82 Southwark Bridge Rd",
    country: "LONDON",
    postcode: "SE1 0EX",
    phone: "0207 183 5875",
    email: "hello@showandtelluk.com",
  },
  {
    id: nanoid(),
    headingAdress: "US",
    company: "Show And Tell LLC",
    region: "244 Fifth Ave Suite S223",
    country: "NEW YORK",
    postcode: "NY 10001",
    phone: "929 313 7875",
    email: "hello@showandtelluk.com",
  },
];

export const footerLinks = [
  {
    id: nanoid(),
    socials: ["instagram", "tiktok", "twitter", "youtube"],
  },
];
